name: iamin_Dashboard

on: [pull_request, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - name: Install Dependencies
      run: flutter packages get

    - name: Format
      run: flutter format --set-exit-if-changed lib test

    - name: Analyze
      run: flutter analyze lib test

    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        
    - run: flutter build ios --release --no-codesign
    - name: Create IPA
      run: |
          mkdir Payload && mv build/ios/Release-iphoneos/Runner.app Payload/.
          zip -r Payload.zip Payload
          mv Payload.zip Payload.ipa
          rm -rf Payload
    - name: Upload IOS Release Asset
      id: upload-ios-release-asset
      uses: softprops/action-gh-release@v1
      with:
          files: Payload.ipa
          name: iamin_dashboard.ipa
          
    - run: flutter build apk --release   
    - name: Upload Android Release Asset
      id: upload-android-release-asset
      uses: softprops/action-gh-release@v1
      with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: iamin_dashboard.apk
