name: iamin_Dashboard

on: [pull_request, push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - name: Install Dependencies
      run: flutter packages get

    - name: Format
      run: flutter format --set-exit-if-changed lib test

    - name: Analyze
      run: flutter analyze lib test

    - name: Run tests
      run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: coverage/index.html # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

